title: HL7 EU Terminology Server
description: Documentation
theme: just-the-docs

url: https://hl7-eu.github.io/tx.hl7europe.eu

#aux_links:
#  Template Repository: https://github.com/just-the-docs/just-the-docs-template
https://github.com/hl7-eu/tx.hl7europe.eu